# Generated by Django 2.1.7 on 2019-05-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashtag',
            field=models.CharField(blank=True, max_length=50, verbose_name='hashtag'),
        ),
    ]
